name: scene-actions
run-name: ${{ github.actor }} scene runs                         
on: [push]
jobs:
  runs-helloworld-with-zulu-17: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - run: javac example/*.java
      - run: java example/Scene.java
